### ISSUE TITLE
Pip install on mac fails

### ISSUE THREAD

**Issue by fran-babylon** [disi-unibo-nlp/nlg-metricverse#3]
**Describe the bug**
Pip installing fails on mac

**To Reproduce**
`pip install nlg-metricverse`

**Exception Traceback (if available)**
`% pip install nlg-metricverse
Looking in indexes: https://pypi.org/simple, https://nlp.circleci:****@artifactory.ops.babylontech.co.uk/artifactory/api/pypi/babylon-pypi/simple
Collecting nlg-metricverse
  Using cached nlg-metricverse-0.1.0.tar.gz (81 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/francesco.moramarco/gvenv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/francesco.moramarco/gvenv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/francesco.moramarco/gvenv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/jj/s730cphx5cq73f0xd964gn780000gp/T/pip-build-env-fl5ohxlq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/jj/s730cphx5cq73f0xd964gn780000gp/T/pip-build-env-fl5ohxlq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/jj/s730cphx5cq73f0xd964gn780000gp/T/pip-build-env-fl5ohxlq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/jj/s730cphx5cq73f0xd964gn780000gp/T/pip-build-env-fl5ohxlq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 153, in <module>
        File "<string>", line 71, in get_requirements
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Environment Information:**
 - OS: macOS Monterey (v12.6.1)
 - nlgmetricverse version: latest on pypi

**Comment by andreazammarchi3** [comment]
There was an error publishing the package, the requirements.txt file was not included. This bug will be fixed in the next release. Thanks for the warning.
